
export const WALLETBANK_ADDRESS = "0x3376Fbf252F94C3E63b1eaBd53412D64542f1B39";
export const WALLETBANK_ABI = [
  { "inputs": [], "stateMutability": "payable", "type": "function", "name": "deposit", "outputs": [] },
  { "inputs": [{ "internalType": "uint256", "name": "amount", "type": "uint256" }], "name": "withdraw", "outputs": [], "stateMutability": "nonpayable", "type": "function" },
  { "inputs": [{ "internalType": "address", "name": "to", "type": "address" }, { "internalType": "uint256", "name": "amount", "type": "uint256" }], "name": "transferEth", "outputs": [], "stateMutability": "nonpayable", "type": "function" },
  { "inputs": [{ "internalType": "address", "name": "_user", "type": "address" }], "name": "getBalance", "outputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }], "stateMutability": "view", "type": "function" }
];

export const WBT_ADDRESS = "0x6F525dd6Bb4396971154A75eE02007d958360132";
export const WBT_ABI = [
  { "constant": true, "inputs": [{ "name": "account", "type": "address" }], "name": "balanceOf", "outputs": [{ "name": "", "type": "uint256" }], "type": "function", "stateMutability": "view" },
  { "constant": true, "inputs": [], "name": "decimals", "outputs": [{ "name": "", "type": "uint8" }], "type": "function", "stateMutability": "view" },
  { "constant": true, "inputs": [], "name": "symbol", "outputs": [{ "name": "", "type": "string" }], "type": "function", "stateMutability": "view" },
  { "constant": false, "inputs": [{ "name": "to", "type": "address" }, { "name": "value", "type": "uint256" }], "name": "transfer", "outputs": [{ "name": "", "type": "bool" }], "type": "function", "stateMutability": "nonpayable" }
];

export const TRADINGGAME_ADDRESS = "0x1269661f3c03860E49405794977cDC63fdaa1f1e"; 
export const TRADINGGAME_ABI = [
  { "inputs": [{ "internalType": "contract IERC20", "name": "_token", "type": "address" }], "stateMutability": "nonpayable", "type": "constructor" },
  { "inputs": [], "name": "entryFee", "outputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }], "stateMutability": "view", "type": "function" },
  { "inputs": [], "name": "gameFee", "outputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }], "stateMutability": "view", "type": "function" },
  { "inputs": [], "name": "owner", "outputs": [{ "internalType": "address", "name": "", "type": "address" }], "stateMutability": "view", "type": "function" },
  { "inputs": [], "name": "token", "outputs": [{ "internalType": "contract IERC20", "name": "", "type": "address" }], "stateMutability": "view", "type": "function" },
  { "inputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }], "name": "players", "outputs": [{ "internalType": "address", "name": "playerAddress", "type": "address" }, { "internalType": "string", "name": "name", "type": "string" }, { "internalType": "uint256", "name": "balance", "type": "uint256" }, { "internalType": "bool", "name": "isActive", "type": "bool" }, { "internalType": "uint256", "name": "lastClaimed", "type": "uint256" }, { "internalType": "uint256", "name": "completedTaskCount", "type": "uint256" }], "stateMutability": "view", "type": "function" },
  { "inputs": [{ "internalType": "address", "name": "", "type": "address" }], "name": "playerInfo", "outputs": [{ "internalType": "address", "name": "playerAddress", "type": "address" }, { "internalType": "string", "name": "name", "type": "string" }, { "internalType": "uint256", "name": "balance", "type": "uint256" }, { "internalType": "bool", "name": "isActive", "type": "bool" }, { "internalType": "uint256", "name": "lastClaimed", "type": "uint256" }, { "internalType": "uint256", "name": "completedTaskCount", "type": "uint256" }], "stateMutability": "view", "type": "function" },
  { "inputs": [{ "internalType": "address", "name": "", "type": "address" }], "name": "hasJoined", "outputs": [{ "internalType": "bool", "name": "", "type": "bool" }], "stateMutability": "view", "type": "function" },
  { "inputs": [{ "internalType": "uint256", "name": "_fee", "type": "uint256" }], "name": "setFee", "outputs": [], "stateMutability": "nonpayable", "type": "function" },
  { "inputs": [], "name": "joinGame", "outputs": [], "stateMutability": "payable", "type": "function" },
  { "inputs": [{ "internalType": "uint256", "name": "_petId", "type": "uint256" }], "name": "buyPet", "outputs": [], "stateMutability": "nonpayable", "type": "function" },
  { "inputs": [{ "internalType": "uint256", "name": "_petId", "type": "uint256" }, { "internalType": "uint256", "name": "_price", "type": "uint256" }], "name": "sellPet", "outputs": [], "stateMutability": "nonpayable", "type": "function" },
  { "inputs": [{ "internalType": "uint256", "name": "_petId", "type": "uint256" }], "name": "feedPet", "outputs": [], "stateMutability": "nonpayable", "type": "function" },
  { "inputs": [{ "internalType": "uint256", "name": "_petId", "type": "uint256" }, { "internalType": "uint256", "name": "_price", "type": "uint256" }], "name": "petForSale", "outputs": [], "stateMutability": "nonpayable", "type": "function" },
  { "inputs": [{ "internalType": "uint256", "name": "_petId", "type": "uint256" }], "name": "cancelPetSale", "outputs": [], "stateMutability": "nonpayable", "type": "function" },
  { "inputs": [], "name": "getAllPets", "outputs": [{ "components": [{ "internalType": "uint256", "name": "id", "type": "uint256" }, { "internalType": "string", "name": "name", "type": "string" }, { "internalType": "string", "name": "gender", "type": "string" }, { "internalType": "uint256", "name": "level", "type": "uint256" }, { "internalType": "string", "name": "types", "type": "string" }, { "internalType": "uint256", "name": "hunger", "type": "uint256" }, { "internalType": "uint256", "name": "hapiness", "type": "uint256" }, { "internalType": "uint256", "name": "health", "type": "uint256" }, { "internalType": "address", "name": "owner", "type": "address" }, { "internalType": "uint256", "name": "price", "type": "uint256" }, { "internalType": "bool", "name": "isForSale", "type": "bool" }, { "internalType": "uint256", "name": "likes", "type": "uint256" }], "internalType": "struct TradingGame.Pet[]", "name": "", "type": "tuple[]" }], "stateMutability": "view", "type": "function" },
  { "inputs": [{ "internalType": "uint256", "name": "_petId", "type": "uint256" }], "name": "likePet", "outputs": [], "stateMutability": "payable", "type": "function" },
  { "inputs": [], "name": "dailyReward", "outputs": [], "stateMutability": "nonpayable", "type": "function" },
  { "inputs": [{ "internalType": "uint256", "name": "_taskId", "type": "uint256" }], "name": "completeTask", "outputs": [], "stateMutability": "nonpayable", "type": "function" },
  { "inputs": [{ "internalType": "address", "name": "_player", "type": "address" }], "name": "checkAllTasksCompleted", "outputs": [{ "internalType": "bool", "name": "", "type": "bool" }], "stateMutability": "view", "type": "function" },
  { "inputs": [{ "internalType": "address", "name": "_player", "type": "address" }], "name": "getCompletedTasks", "outputs": [{ "internalType": "uint256[]", "name": "", "type": "uint256[]" }], "stateMutability": "view", "type": "function" },
  { "inputs": [{ "internalType": "address", "name": "_playerAddress", "type": "address" }, { "internalType": "uint256", "name": "_petId", "type": "uint256" }], "name": "getPlayerPetBalance", "outputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }], "stateMutability": "view", "type": "function" },
  { "inputs": [{ "internalType": "uint256", "name": "_id", "type": "uint256" }, { "internalType": "string", "name": "_name", "type": "string" }, { "internalType": "string", "name": "_gender", "type": "string" }, { "internalType": "uint256", "name": "_level", "type": "uint256" }, { "internalType": "string", "name": "_types", "type": "string" }, { "internalType": "uint256", "name": "_hunger", "type": "uint256" }, { "internalType": "uint256", "name": "_hapiness", "type": "uint256" }, { "internalType": "uint256", "name": "_health", "type": "uint256" }, { "internalType": "address", "name": "_owner", "type": "address" }, { "internalType": "uint256", "name": "_price", "type": "uint256" }, { "internalType": "bool", "name": "_isForSale", "type": "bool" }, { "internalType": "uint256", "name": "_likes", "type": "uint256" }], "name": "addPet", "outputs": [], "stateMutability": "nonpayable", "type": "function" },
  { "inputs": [], "name": "defaultPets", "outputs": [], "stateMutability": "nonpayable", "type": "function" },
  { "inputs": [{ "internalType": "string", "name": "_name", "type": "string" }, { "internalType": "string", "name": "_description", "type": "string" }, { "internalType": "uint256", "name": "_reward", "type": "uint256" }, { "internalType": "uint8", "name": "_taskType", "type": "uint8" }], "name": "addTask", "outputs": [], "stateMutability": "nonpayable", "type": "function" },
  { "inputs": [], "name": "defaultTasks", "outputs": [], "stateMutability": "nonpayable", "type": "function" },
  { "inputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }], "name": "tasks", "outputs": [{ "internalType": "uint256", "name": "id", "type": "uint256" }, { "internalType": "string", "name": "name", "type": "string" }, { "internalType": "string", "name": "description", "type": "string" }, { "internalType": "uint256", "name": "reward", "type": "uint256" }, { "internalType": "bool", "name": "isCompleted", "type": "bool" }, { "internalType": "uint8", "name": "taskType", "type": "uint8" }], "stateMutability": "view", "type": "function" },
  { "inputs": [{ "internalType": "address", "name": "", "type": "address" }, { "internalType": "uint256", "name": "", "type": "uint256" }], "name": "completedTasks", "outputs": [{ "internalType": "bool", "name": "", "type": "bool" }], "stateMutability": "view", "type": "function" },
  { "inputs": [{ "internalType": "address", "name": "", "type": "address" }, { "internalType": "uint256", "name": "", "type": "uint256" }], "name": "playerPet", "outputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }], "stateMutability": "view", "type": "function" },
  { "inputs": [{ "internalType": "address", "name": "", "type": "address" }, { "internalType": "uint256", "name": "", "type": "uint256" }], "name": "playerPetIds", "outputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }], "stateMutability": "view", "type": "function" },
  { "inputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }], "name": "pets", "outputs": [{ "internalType": "uint256", "name": "id", "type": "uint256" }, { "internalType": "string", "name": "name", "type": "string" }, { "internalType": "string", "name": "gender", "type": "string" }, { "internalType": "uint256", "name": "level", "type": "uint256" }, { "internalType": "string", "name": "types", "type": "string" }, { "internalType": "uint256", "name": "hunger", "type": "uint256" }, { "internalType": "uint256", "name": "hapiness", "type": "uint256" }, { "internalType": "uint256", "name": "health", "type": "uint256" }, { "internalType": "address", "name": "owner", "type": "address" }, { "internalType": "uint256", "name": "price", "type": "uint256" }, { "internalType": "bool", "name": "isForSale", "type": "bool" }, { "internalType": "uint256", "name": "likes", "type": "uint256" }], "stateMutability": "view", "type": "function" }
];